### ISSUE TITLE
Sentence throughput regressions

### ISSUE THREAD

**Issue by graemenail** [hplt-project/OpusTrainer#33]
Current we don't have any measures on the performance impact of code changes. 

We should have a test that benchmarks e.g. run-time to process 1M sentences for each filter. Filters would need to provide a representative (set of) configurations to test over.

**Comment by XapaJIaMnu** [comment]
We should record typical marian training speed (WPS) on a given hardware and compare what is the throughput we can achieve with OpusTrainer. We are probably quite suboptimal with heavy use of placeholders.

**Comment by XapaJIaMnu** [comment]
This is critical,  we are wasting tremendous amount of GPU time because we wait on data production.  GPUs idle when training student models, essentially

**Comment by graemenail** [comment]
We should put some numbers here. How does it scale with (opustrainer) batch size?

**Comment by XapaJIaMnu** [comment]
I'll do some profiling. This didn't use to be this slow when doing terminology, i'll have to see what happened.

**Comment by XapaJIaMnu** [comment]
Some numbers:
```yml
# Datasets are already TSV files
datasets:
  clean: /tmp/clean.zhen.100krep

stages:
  - start

start:
  - clean  1
  - until clean 1

#modifiers:
  #- UpperCase: 0.1
  #- TitleCase: 0.1
  #- Tags: 0.1
  #  custom_detok_src: zh

seed: 1111
trainer: cat
```
Varying application of tags (with and without detokenization), UpperCase and TittleCase (albeit those would only be applied on the target side but oh well good enough for benchmarking)

command used:
```bash
time opustrainer-train -c CONFIG.YML -d cat > /dev/null
```
Checked current main and a version from 1.5 months ago when the logger was merged:

| Type             | 1f287a5 | f695e04 |
|------------------|--------:|--------:|
| No Modifier      |      6s |      6s |
| UpperCase        |      6s |      6s |
| TitleCase        |      8s |      8s |
| Tags             |    205s |     27s |
| Tags + detok_src |    287s |    121s |

We have 9x regression of performance when using tags after the tags rewrite, plus the detokenizer is really slow. We probably want the detokenizer to be multithreaded.
