### ISSUE TITLE
"Out-of-bound alignment pairs" for alignments trained with Sentencepiece tokenizer

### ISSUE THREAD

**Issue by eu9ene** [hplt-project/OpusTrainer#38]
I use alignments trained with [this script](https://github.com/mozilla/firefox-translations-training/blob/main/pipeline/alignment/generate-alignment-and-shortlist.sh). They're based on Septencepiece tokenization. I see that currently Opustrainer always runs str.split for tokenization before parsing alignments even if the spm vocab is provided in the config, so the number of tokens never matches. I think some of this is discussed in https://github.com/hplt-project/OpusTrainer/issues/29

Basically, my full dataset is filtered with this warning:
```
[Trainer] [WARNING] Skipping line because of exception: ValueError('Out-of-bound alignment pairs')
```
Config:
```
datasets:
  # Original parallel corpus + alignments
  original: /data/rw/evgeny/data/ru-en/better-teacher/test_opustrainer/corpus.ruen.tsv

stages:
  - train

train:
  - original 1.0
  - until original 1 

modifiers:
- UpperCase: 0.05 # Apply randomly to 5% of sentences
- TitleCase: 0.05
- Typos: 0.05
- Tags: 0.05
  augment: 0.05 
  replace: 0.05 
  spm_vocab: /data/rw/evgeny/models/ru-en/better-teacher/vocab/vocab.spm
seed: 1111
num_fields: 3
```

How I run marian: https://github.com/mozilla/firefox-translations-training/blob/40091840a24dd30cf50f4bcf0470645469ee75a8/pipeline/train/train.sh#L77
