### ISSUE TITLE
Support training arguments for training stages

### ISSUE THREAD

**Issue by eu9ene** [hplt-project/OpusTrainer#44]
After switching from pre-training and fine-tuning tasks to OpusTrainer with multiple stages we ran into issue with early-stopping. We usually want to train early stages for a fixed number of epochs and then train the last stage until the metrics are not improving and it's stopped by Marian. This Marian parameter and probably some others should be configurable per stage. I assume we could add them to the training config:

```
start:
  mix:
  - clean 0.8
  - medium 0.2
  - dirty 0
  - until clean 2 # Until two epochs of clean
  modifiers:
    - UpperCase: 0.05
    - TitleCase: 0.05
  arguments:
    - early-stopping: 30
```
