### ISSUE TITLE
Error while parsing modifier arguments

### ISSUE THREAD

**Issue by eu9ene** [hplt-project/OpusTrainer#50]
```yaml
modifiers:
- Merge: 0.01
  min_lines: 2 # Minimum lines to merge together
  max_lines: 4 # Maximum lines to merge together
```
leads to error
```
raise CurriculumLoaderError(f"could not initialize modifier '{name}': {exc!s}") from exc
opustrainer.trainer.CurriculumLoaderError: could not initialize modifier 'Merge': MergeModifier.__init__() got an unexpected keyword argument 'min_lines'
```
and
```yaml
modifiers:
- Noise: 0.0005
  min_word_length: 2 # Minimum word length for each word in the noisy sentence
  max_word_length: 5 # Maximum word length for each word in the noisy sentence
  max_words: 6 # Maximum number of words in each noisy sentence
```
to
```
 line 535, in _load_modifier
    raise CurriculumLoaderError(f"could not initialize modifier '{name}': {exc!s}") from exc
opustrainer.trainer.CurriculumLoaderError: could not initialize modifier 'Noise': NoiseModifier.__init__() got an unexpected keyword argument 'min_word_length'

```
